version: 0.0.1

server:
  applicationConnectors:
  - type: http
    port: 9000

database:
  driverClass: org.hsqldb.jdbcDriver
  user: sa
#  password:
  url: jdbc:hsqldb:file:database.dat;shutdown=true
  properties:
    charSet: UTF-8
  validationQuery: "SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS"
  properties:
    hibernate.dialect: org.hibernate.dialect.HSQLDialect
    hibernate.show_sql: true
    hibernate.hbm2ddl.auto: validate # validates schema when service is started